### ISSUE TITLE
Unable to use client certificate chain

### ISSUE THREAD

**Issue by MuniekMg** [sroebert/mqtt-nio#11]
Hi, great project, thank you for your work! :)

From version 4.6 we are unable to pass client certificate chain, because client certificate is passed by SecIdentity and SecIndetity is unable to hold certificate chain. I have created PR to your project solving this problem: https://github.com/sroebert/mqtt-nio/pull/10

I asked Apple engineer about my solution and he confirmed that this is correct solution:
https://developer.apple.com/forums/thread/715174

All tests passed.

**Comment by sroebert** [comment]
Thank you for the improvements. I have merged, but changed the enum back into a separate new property for `clientIdentityCertificates` in order to make it backwards compatible. The enum will go on the list of breaking changes for version 3.0 to improve the API.

**Comment by MuniekMg** [comment]
Great 👍  Thank you :)
