### ISSUE TITLE
Xcode is crashing during exctracting the IPA, with MQTT NIO

### ISSUE THREAD

**Issue by muralivm** [sroebert/mqtt-nio#5]
Hey, 

I have integrated the MQTT NIO version 2.5.0 to my current watch OS target. Everything works fine I am able to access the API during my development.
But I am facing an Xcode crash while exporting IPA from Archive.

1) Running on the device and simulator --> No issues
2) Archiving is successful.

> **3) Exporting IPA from Archive --> Xcode is crashing.**
I have tested with other package dependencies, i am able to export IPA successfully.

Please do the needful

**Comment by sroebert** [comment]
I think this might be the same issue as #6, will have a look tomorrow.

**Comment by sroebert** [comment]
This should be fixed in the latest release (2.6.0).
