### ISSUE TITLE
App Store Connect - Invalid bundle: Bitcode failed to compile 

### ISSUE THREAD

**Issue by azzastudios** [sroebert/mqtt-nio#6]
Hi

I am trying to upload my app to the app store connect using this package. But I'm getting this error when uploading:

`ITMS-90562: Invalid Bundle - Bitcode failed to compile for your watchOS binary because it includes assembly source code or inline assembly.`

I found that it is probably related to dependency on the Swift-NIO-SSL package. But haven't been able to work out a solution.

Maybe you have a solution to this problem.

Thanks in advance.

**Comment by sroebert** [comment]
I will have a look tomorrow, I might have to conditionally import it, I think I’ve seen similar handlings in other libraries.

**Comment by sroebert** [comment]
Ok, this requires some changes in SSL handling for watchOS targets, I will make a fix as soon as possible, but it will take me a few more days to find time for this.

**Comment by sroebert** [comment]
This should be fixed in the latest release (2.6.0).
