### ISSUE TITLE
callback for subscribe message

### ISSUE THREAD

**Issue by arrow53** [sroebert/mqtt-nio#8]
I'm using an `MQTTClient`. I want to subscribe and have a callback when I receive a message. I'm using version 2.0.0 (also tried with 2.6.0). This is for a watchOS app

If I do this
```
    init() {
        client.connect()
        
        client.whenMessage { message in
            print("Received: \(message)")
        }
    }
```

I get this
`Value of type 'MQTTClient' has no member 'whenMessage'`

**Comment by sroebert** [comment]
Could you post the whole Swift file where you can reproduce this error and post that here. I am sure there must be something else wrong with the code, as I am using this in my own projects and the `MQTTClient` definitely has `whenMessage` as a function. You did not for example create a class of your own named `MQTTClient`?

The following works fine for me:

```
import MQTTNIO

class Test {
    private var client: MQTTClient
    
    init() {
        client = MQTTClient(configuration: MQTTConfiguration(url: URL(string: "mqtt://test")!))
        client.connect()
        
        client.whenMessage { message in
            print("Received: \(message)")
        }
    }
}
```

**Comment by arrow53** [comment]
Creating a new file `Mqtt.swift` and adding in the above code I get these errors
```
Mqtt.swift:15:44: Cannot find 'MQTTConfiguration' in scope
Mqtt.swift:18:16: Value of type 'MQTTClient' has no member 'whenMessage'
```

My code looks like this
```
import SwiftUI
import MQTTNIO

struct ContentView: View {
    let client = MQTTClient(
        host: "192.168.2.3",
        port: 1883,
        identifier: "watch",
        eventLoopGroupProvider: .createNew
    )
    let qos: MQTTQoS = .atMostOnce
    
    init() {
        let ConnectResult = client.connect()
        let SubInfo = MQTTSubscribeInfo(
            topicFilter: "weather/t2",
            qos: qos)
        let SubClient = client.subscribe(to: [SubInfo])
                
        // error here
        client.whenMessage { message in
            print("Received: \(message)")
        }
    }
    
    var body: some View {
        Text("Hello, World!")
            .padding()
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        Group {
            ContentView()
        }
    }
}
```

**Comment by sroebert** [comment]
The errors you are posting do not match the file you posted.

This is what I am getting:

<img width="725" alt="Screenshot 2022-08-29 at 07 59 29" src="https://user-images.githubusercontent.com/81575/187132870-c0bd762e-8774-4915-a192-9865ec454b52.png">

First, you cannot create `MQTTClient` like that, you have to pass a configuration object. Second, `MQTTSubscribeInfo` does not exist, it should be `MQTTSubscription`. I would suggest you look more closely at the API in the code of this repo.

I'm assuming you are new to Swift and SwiftUI. You cannot just create an instance of a class like `MQTTClient` inside a view like this. Every time the view is recreated (which can happen at any change of data in SwiftUI), the client will be recreated. Most likely the client will also not be retained like this. You would have to use an `ObservableObject` stored using `@StateObject` instead. I would suggest you follow some more tutorials on Swift and SwiftUI (e.g. https://www.hackingwithswift.com is a good start)

Just to show you how it should be working, here's an alteration of the code:

```swift
import SwiftUI
import MQTTNIO

struct ContentView: View {
    
    // MARK: - Private Vars
    
    @StateObject private var viewModel = ContentViewModel()
    
    var body: some View {
        Text("Hello, World!")
            .padding()
    }
}

final class ContentViewModel: ObservableObject {
    
    let client = MQTTClient(
        configuration: MQTTConfiguration(
            target: .host("192.168.2.3", port: 1883),
            clientId: "watch"
        )
    )
    
    init() {
        client.whenConnected { [weak self] _ in
            let subscription = MQTTSubscription(
                topicFilter: "weather/t2",
                qos: .atMostOnce
            )
            self?.client.subscribe(to: [subscription])
        }
        client.whenMessage { message in
            print("Received: \(message)")
        }
        
        client.connect()
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        Group {
            ContentView()
        }
    }
}
```

**Comment by arrow53** [comment]
@sroebert thanks so much for the example!
